#!/bin/bash

# Run the KFusion-TornadoVM console/Benchmark mode on whichever backend
# (Metal, OpenCL, or CUDA) the active TornadoVM SDK provides.
#
# Usage:
#   ./scripts/run.sh [backend] [settings-file]
#
# [backend] is optional and only needed when the active TornadoVM SDK has
# more than one backend installed together - it sets that backend's device
# priority so its devices are listed first, e.g.:
#   ./scripts/run.sh opencl
#   ./scripts/run.sh cuda
#   ./scripts/run.sh metal
#
# [settings-file] defaults to conf/bm-traj2.settings, e.g.:
#   ./scripts/run.sh metal conf/bm-traj3.settings

: "${TORNADOVM_HOME:?TORNADOVM_HOME is not set. Install a TornadoVM SDK (Metal, OpenCL, or CUDA backend) and source its setvars.sh first.}"
: "${KFUSION_ROOT:?KFUSION_ROOT is not set. Run 'source source.env' from the repo root first.}"

ARGFILE="${TORNADOVM_HOME}/tornado-argfile"
# Always regenerate: the argfile's JVMCI flags (e.g. --patch-module for JDK 22-26,
# the vendored module-path entry for JDK 27+) are computed from whichever JDK is
# active when it's generated. Only regenerating "if missing" would silently reuse
# stale flags computed under a different JAVA_HOME than the one running this script.
echo "Generating TornadoVM argfile for ${TORNADOVM_HOME}..."
tornado --generate-argfile

JARS=$(echo ${KFUSION_ROOT}/target/*.jar | tr ' ' ':')

BACKEND_PRIORITY=()
if [ -n "$1" ]; then
    BACKEND_PRIORITY=("-Dtornado.$1.priority=100")
fi

SETTINGS="${2:-conf/bm-traj2.settings}"

echo "kfusion kfusion.tornado.Benchmark ${SETTINGS}"

# Use JAVA_HOME's java explicitly, not whatever "java" resolves to on PATH:
# the argfile above was just generated by tornado --generate-argfile, which
# (per its wrapper script) always runs under "$JAVA_HOME/bin/java" - so the
# JVM that consumes the argfile must be that same JDK, or the JDK-version-
# specific flags/module-path baked into it (see comment above) can mismatch
# whatever JDK a stale PATH entry happens to hand back for bare "java".
"${JAVA_HOME}/bin/java" @"${ARGFILE}" \
    -Xms2G -Xmx20G \
    -Dtornado.kernels.coarsener=False \
    -Dtornado.enable.fix.reads=False \
    -Dtornado.compiler.fullInlining=True \
    -Dtornado.benchmarking=False \
    -Dtornado.profiler=False \
    -Dtornado.log.profiler=False \
    -Dlog4j.configurationFile="${KFUSION_ROOT}/conf/log4j2.xml" \
    "${BACKEND_PRIORITY[@]}" \
    -cp "${CLASSPATH}:${JARS}" \
    kfusion.tornado.Benchmark "${SETTINGS}"
